name: Renovate
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - develop

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v1.0.0
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
